// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/AdongoJr2/technoprise-backend/ent/blogpost"
	"github.com/AdongoJr2/technoprise-backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blogpostMixin := schema.BlogPost{}.Mixin()
	blogpostMixinFields0 := blogpostMixin[0].Fields()
	_ = blogpostMixinFields0
	blogpostFields := schema.BlogPost{}.Fields()
	_ = blogpostFields
	// blogpostDescCreateTime is the schema descriptor for create_time field.
	blogpostDescCreateTime := blogpostMixinFields0[0].Descriptor()
	// blogpost.DefaultCreateTime holds the default value on creation for the create_time field.
	blogpost.DefaultCreateTime = blogpostDescCreateTime.Default.(func() time.Time)
	// blogpostDescUpdateTime is the schema descriptor for update_time field.
	blogpostDescUpdateTime := blogpostMixinFields0[1].Descriptor()
	// blogpost.DefaultUpdateTime holds the default value on creation for the update_time field.
	blogpost.DefaultUpdateTime = blogpostDescUpdateTime.Default.(func() time.Time)
	// blogpost.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	blogpost.UpdateDefaultUpdateTime = blogpostDescUpdateTime.UpdateDefault.(func() time.Time)
	// blogpostDescTitle is the schema descriptor for title field.
	blogpostDescTitle := blogpostFields[0].Descriptor()
	// blogpost.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	blogpost.TitleValidator = blogpostDescTitle.Validators[0].(func(string) error)
	// blogpostDescSlug is the schema descriptor for slug field.
	blogpostDescSlug := blogpostFields[1].Descriptor()
	// blogpost.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	blogpost.SlugValidator = blogpostDescSlug.Validators[0].(func(string) error)
	// blogpostDescContent is the schema descriptor for content field.
	blogpostDescContent := blogpostFields[2].Descriptor()
	// blogpost.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	blogpost.ContentValidator = blogpostDescContent.Validators[0].(func(string) error)
	// blogpostDescExcerpt is the schema descriptor for excerpt field.
	blogpostDescExcerpt := blogpostFields[3].Descriptor()
	// blogpost.ExcerptValidator is a validator for the "excerpt" field. It is called by the builders before save.
	blogpost.ExcerptValidator = func() func(string) error {
		validators := blogpostDescExcerpt.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(excerpt string) error {
			for _, fn := range fns {
				if err := fn(excerpt); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
